### PR TITLE
US11669 - Add Japanese support  to Lucene++

### PR DESCRIPTION
**Pull request by dtian2015**
-Details:
  Convert Japanese support files (and all dependent core files that are missing in original Lucene++) from Java Lucene 3.6 to C++ and add into Lucene++

   Reviewers, the NVivo generated lucene++ xcode project file is under `europa/external/slayer/build/tpb/build_luceneplusplus-XXXXX/build`

-Link:
US11669 - https://rally1.rallydev.com/#/68708670732d/detail/userstory/208937241668
The Java Lucene 3.6 source could be found here: https://archive.apache.org/dist/lucene/java/3.6.0/

-Note:
1. Normally a .h and .cpp file are created from each java file.
2. There are 3 inter-dependent template classes `FST<T>, Builder<T> and NodeHash<T>` in 3 java files, but this is causing issues in C++, so just apply the `inclusion model` to have all 3 template classes (declaration and definition) in ONE `FST.h` file after conversion.
3. Most of java source code comments (including TODOs)  were kept and carried over.
4. Make sure converted files conform to lucene++ styles.
5. The added (or modified) files were clang-formatted.  
6. The environment `LUCENE_DICT_PATH` must be defined to allow dictionary data files to be loaded properly
 7.  The `ENABLE_TEST` needs to be changed to `ON` in `third_party/luceneplusplus/CMakeLists.txt` to allow lucene++ unit test project to be compiled and executed.
8. To allow text search from WFQ result word (base form word which might not always be the same as term text) to return correct result , a `Japanese base form to term word(s) mapping` map is serialized into source index to allow caller to retrieve mapping then use it to generate term word(s) from base form for text search. This is our customisation NOT in Java Lucene++ library. The approach is similar to Windows team Lucene.Net customisation.
9. Boot serialization component is now used in Lucene++

-Background Info:
The conversion and enhancement to lucene++ has to be done before we can support Japanese in NVivo Mac word frequency queries.

-FYI: @rusminsusanto

### CODE REVIEW

**Comment by DarrenFordQSR** [comment]
Absolutely wonderful work mate.

**Comment by dtian2015** [comment]
Ready for formal review. Please note that this PR will be tested on later Slayer integration PR  as there is no build job setup for `QSRINT\LucenePlusPlus` yet.

**Comment by DarrenFordQSR** [comment]
Hey @dtian2015 

Can I ask you to update the wiki page (https://qsrinternational.atlassian.net/wiki/spaces/MAC/pages/531529736/Japanese+Chinese+Support+in+WFQ) to add in (at the top)

1. Which method you went with (I know this, but I'm thinking forward to when we have 100 additional devs working on the Mac product 😁 )
2. A link to the original java 3.6 code that was converted.
3. A basic discussion of how/where it is integrated within Slayer so we can find it in the case of bugs or issues

Great work!

**Comment by dtian2015** [comment]
Sure will update wiki with those details.

It’s mainly some high level stuff, some implementation details will be in PR summary or commit messages.

Cheers,
Daniel Tian

**Comment by dtian2015** [comment]
Updated wiki page https://qsrinternational.atlassian.net/wiki/spaces/MAC/pages/531529736/Japanese+Chinese+Support+in+WFQ with added sections at the end

**Comment by DarrenFordQSR** [comment]
👍 👍

**Pull request merged**
